name: Docker Image CI on Release (Multi-Arch)

on:
  release:
    types: [published] # This trigger runs the workflow when a release is published

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up QEMU (Required for multi-arch builds)
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }} # You'll need to set this secret in your repo
        password: ${{ secrets.DOCKER_PASSWORD }} # You'll need to set this secret in your repo

    - name: Extract release tag
      id: get_tag
      run: echo "RELEASE_TAG=${GITHUB_REF#refs/tags/}" >> "$GITHUB_OUTPUT"
      # Using GITHUB_REF_NAME is simpler if you want the tag name directly (e.g., v1.0.0)
      # run: echo "RELEASE_TAG=${{ github.ref_name }}" >> "$GITHUB_OUTPUT"

    - name: Build and Push Docker image for arm64
      # Only push the "latest" tag for the release-specific image name
      run: |
        FULL_IMAGE_NAME="${{ secrets.DOCKER_USERNAME }}/gita-server-${{ steps.get_tag.outputs.RELEASE_TAG }}"
        
        docker buildx build \
          --platform linux/arm64 \
          --file Dockerfile \
          --tag "${FULL_IMAGE_NAME}:latest" \
          --push \
          .
